package com.sinensia.hellotestrobobar;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class RobobarSuitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeAll
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void productoRobaCola1() {
    // Test name: ProductoRobaCola1
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€1.25"));
  }

  @Test
  public void productoRobaCola2() {
    // Test name: ProductoRobaCola2
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 4 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €2.50
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.50"));
  }

  @Test
  public void productoRoboBeer1() {
    // Test name: ProductoRoboBeer1
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €2.00
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.00"));
  }

  @Test
  public void productoRoboBeer2() {
    // Test name: ProductoRoboBeer2
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €4.00
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€4.00"));
  }

  @Test
  public void productoRobWine1() {
    // Test name: ProductoRobWine1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 | 
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    // 4 | assertText | css=tr:nth-child(4) > .ng-binding | €3.00
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.00"));
  }

  @Test
  public void productoRobWine2() {
    // Test name: ProductoRobWine2
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    // 4 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €6.00
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.00"));
  }

  @Test
  public void todosProductos() {
    // Test name: TodosProductos
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1035x1013 |
    driver.manage().window().setSize(new Dimension(1035, 1013));
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    // 5 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    // 6 | assertText | css=tr:nth-child(4) > .ng-binding | €6.25
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.25"));
  }
}
