package com.sinensia.hellotestrobobar.pageobject;// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class CartSuitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  CartPage cartPage;
  CheckoutPage checkoutPage;
  OrderPage orderPage;

  @BeforeAll
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @BeforeEach
  public void setupTest(){
    cartPage = new CartPage(driver);
    checkoutPage = new CheckoutPage(driver);
    orderPage = new OrderPage(driver);
    driver.get("http://localhost:3000/");
  }

  @AfterAll
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void colaTest1() {
    //Add a cola
    cartPage.addColaButton.click();
    //Total must be €1.25
    assertEquals(cartPage.totalField.getText(), "€1.25");
  }

  @Test
  public void colaTest2() {
    //Add a cola
    cartPage.addColaButton.click();
    //Add a cola
    cartPage.addColaButton.click();
    //Total must be €2.50
    assertEquals(cartPage.totalField.getText(), "€2.50");
  }

  @Test
  public void beerTest1() {
    //Add a beer
    cartPage.addBeerButton.click();
    //Total must be €2.00
    assertEquals(cartPage.totalField.getText(), "€2.00");
  }

  @Test
  public void beerTest2() {
    //Add a beer
    cartPage.addBeerButton.click();
    //Add a beer
    cartPage.addBeerButton.click();
    //Total must be €4.00
    assertEquals(cartPage.totalField.getText(), "€4.00");
  }

  @Test
  public void wineTest1() {
    //Add a wine
    cartPage.addWineButton.click();
    //Total must be €3.00
    assertEquals(cartPage.totalField.getText(), "€3.00");
  }

  @Test
  public void wineTest2() {
    //Add a wine
    cartPage.addWineButton.click();
    //Add a wine
    cartPage.addWineButton.click();
    //Total must be €6.00
    assertEquals(cartPage.totalField.getText(), "€6.00");
  }

  @Test
  public void allProducts() {
    //Add a cola
    cartPage.addColaButton.click();
    //Add a beer
    cartPage.addBeerButton.click();
    //Add a wine
    cartPage.addWineButton.click();
    //Total must be €1.25 + €2.00 + €3.00
    assertEquals(cartPage.totalField.getText(), "€6.25");
  }

  @Test
  public void confirmCola() {
    //Add a cola
    cartPage.addColaButton.click();
    //Press checkout
    cartPage.checkoutButton.click();
    //Press confirm button
    checkoutPage.orderButton.click();
    //See confirmation screen
    assertEquals(orderPage.confirmationMessage.getText(), "Coming right up! ~bzzzt~");
  }
}
